version: '3'
services:
  app:
    restart: "always"
    build:
      context: ../src
      dockerfile: ../docker/Dockerfile
    command: python app.py
    volumes:
      - ../src:/code
    ports:
      - 5000:5000